repos:
  - repo: local
    hooks:
      - id: palantir-java-format
        name: palantir-java-format
        description: Format Java code with palantir-java-format
        entry: ./.palantir-java-format-wrapper.sh
        language: system
        types: [java]
        pass_filenames: true
