repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-json
          # https://github.com/pre-commit/pre-commit-hooks/issues/1196
    exclude: ^\.vscode/.*\.json$
  - id: check-merge-conflict
  - id: check-shebang-scripts-are-executable
    exclude: ^\.envrc
  - id: check-symlinks
  - id: check-vcs-permalinks
  - id: check-yaml
    args: [--allow-multiple-documents]
    exclude: mkdocs.yaml
  - id: destroyed-symlinks
  - id: end-of-file-fixer
    exclude: ^(LICENSE-header.txt|.*test-random-binary|.*.svg|.*.expected|third_party/.*|.flox/env/manifest.lock)$
  - id: trailing-whitespace
  - id: pretty-format-json
          # https://github.com/pre-commit/pre-commit-hooks/issues/1196
    exclude: ^\.vscode/.*\.json$

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-java
          # Keep this version in sync with the same version in .vscode/settings.json
    args: [--autofix, --aosp, --google-java-formatter-version=1.29.0]

  - id: pretty-format-yaml
    args: [--autofix]

- repo: https://github.com/NixOS/nixfmt
  rev: v1.0.1
  hooks:
  - id: nixfmt-nix

          # https://editorconfig.org check should run AFTER all of the formatters (above)
- repo: https://github.com/editorconfig-checker/editorconfig-checker.python
  rev: 3.4.0
  hooks:
  - id: editorconfig-checker
    exclude: mvnw|src/ch/vorburger/stereotype/Lifecycled.java
